// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreLocation/CoreLocation.h>
#import <MapKit/MapKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface MapController: UIViewController

@property IBOutlet MKMapView * map;
@property IBOutlet UIActivityIndicatorView * activity;
@property IBOutlet UISlider * slider;

-(IBAction) slider_value_changed:(id) sender;

@end

@interface Coordinates: NSObject
-(IBAction) initialize:(id) attrs;
-(IBAction) to_cl;

@end

